# Generated by Django 4.0.3 on 2022-03-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_superuser',
            new_name='superuser',
        ),
    ]
