# Generated by Django 4.0.3 on 2022-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
