# Generated by Django 4.0.3 on 2022-05-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0004_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
