# Generated by Django 4.0.3 on 2022-04-15 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='fields',
            old_name='user_id',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='fields',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fields',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fields',
            name='resume_id',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='field',
        ),
        migrations.AddField(
            model_name='fields',
            name='field_name',
            field=models.CharField(default='ok', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fields',
            name='has_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fields',
            name='sub_fields',
            field=models.ManyToManyField(through='resume.SubField', to='resume.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='user_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfield',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.fields'),
        ),
        migrations.AddField(
            model_name='subfield',
            name='resume_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
