# Generated by Django 4.0.3 on 2022-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_subfield_rename_user_id_fields_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
