# Generated by Django 4.0.3 on 2022-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='User_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='resume',
            name='modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
