# Generated by Django 4.0.3 on 2022-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_resume_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[(1, 'complete'), (2, 'incomplete')], default='incomplete', max_length=20),
            preserve_default=False,
        ),
    ]
