# Generated by Django 4.0.3 on 2022-05-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_customfield_education_experience_personalinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
