# Generated by Django 4.0.3 on 2022-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_alter_personalinformation_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='month_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='month_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
