# Generated by Django 4.0.3 on 2022-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_alter_experience_month_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
