# Generated by Django 4.0.3 on 2022-05-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_education_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='suffix',
            field=models.CharField(default='%', max_length=20),
            preserve_default=False,
        ),
    ]
