# Generated by Django 4.0.3 on 2022-05-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_alter_education_graduation_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='month_end',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='month_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='year_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='year_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
