# Generated by Django 4.0.3 on 2022-05-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_alter_project_month_end_alter_project_month_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalskills',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
