# Generated by Django 4.0.3 on 2022-05-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_alter_technicalskills_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='resume_id',
            new_name='resume',
        ),
    ]
