# Generated by Django 4.0.3 on 2022-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_rename_resume_id_customfield_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='header',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
